# Dataset Description
The MPG dataset is technical spec of cars originaly provided from UCI Machine Learning Repository. The data concerns city-cycle fuel consumption in miles per gallon to be analyzed in terms of 3 multivalued discrete and 5 continuous attributes.
Columns Description
- mpg: miles per galon of fuel (continuous variable).
- cylinders: number of engine cylinders (multi-valued discrete variable).
- displacement: (continuous variable)
- horsepower: the power produced by engine to move the car (continuous variable)
- weight: car weight (continuous variable)
- acceleration: the acceleration an engine can get per second (continuous variable)
- model year: car release year from 1970 to 1982(multi-valued discrete variable)
- origin: car manufacturing place (1 -> USA, 2 -> Europe, 3 -> Asia) (multi-valued discrete variable)
- car name: car model name (unique for each instance)

In [1]:
from google.colab import files
files.upload()

Saving auto-mpg.csv to auto-mpg.csv

{'auto-mpg.csv': b"mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name\r\n18,8,307,130,3504,12,70,1,chevrolet chevelle malibu\r\n15,8,350,165,3693,11.5,70,1,buick skylark 320\r\n18,8,318,150,3436,11,70,1,plymouth satellite\r\n16,8,304,150,3433,12,70,1,amc rebel sst\r\n17,8,302,140,3449,10.5,70,1,ford torino\r\n15,8,429,198,4341,10,70,1,ford galaxie 500\r\n14,8,454,220,4354,9,70,1,chevrolet impala\r\n14,8,440,215,4312,8.5,70,1,plymouth fury iii\r\n14,8,455,225,4425,10,70,1,pontiac catalina\r\n15,8,390,190,3850,8.5,70,1,amc ambassador dpl\r\n15,8,383,170,3563,10,70,1,dodge challenger se\r\n14,8,340,160,3609,8,70,1,plymouth 'cuda 340\r\n15,8,400,150,3761,9.5,70,1,chevrolet monte carlo\r\n14,8,455,225,3086,10,70,1,buick estate wagon (sw)\r\n24,4,113,95,2372,15,70,3,toyota corona mark ii\r\n22,6,198,95,2833,15.5,70,1,plymouth duster\r\n18,6,199,97,2774,15.5,70,1,amc hornet\r\n21,6,200,85,2587,16,70,1,ford maverick\r\n27,4,97,88,2130,14.5,70,3,datsun pl510\r\n26,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan\r\n25,4,110,87,2672,17.5,70,2,peugeot 504\r\n24,4,107,90,2430,14.5,70,2,audi 100 ls\r\n25,4,104,95,2375,17.5,70,2,saab 99e\r\n26,4,121,113,2234,12.5,70,2,bmw 2002\r\n21,6,199,90,2648,15,70,1,amc gremlin\r\n10,8,360,215,4615,14,70,1,ford f250\r\n10,8,307,200,4376,15,70,1,chevy c20\r\n11,8,318,210,4382,13.5,70,1,dodge d200\r\n9,8,304,193,4732,18.5,70,1,hi 1200d\r\n27,4,97,88,2130,14.5,71,3,datsun pl510\r\n28,4,140,90,2264,15.5,71,1,chevrolet vega 2300\r\n25,4,113,95,2228,14,71,3,toyota corona\r\n25,4,98,?,2046,19,71,1,ford pinto\r\n19,6,232,100,2634,13,71,1,amc gremlin\r\n16,6,225,105,3439,15.5,71,1,plymouth satellite custom\r\n17,6,250,100,3329,15.5,71,1,chevrolet chevelle malibu\r\n19,6,250,88,3302,15.5,71,1,ford torino 500\r\n18,6,232,100,3288,15.5,71,1,amc matador\r\n14,8,350,165,4209,12,71,1,chevrolet impala\r\n14,8,400,175,4464,11.5,71,1,pontiac catalina brougham\r\n14,8,351,153,4154,13.5,71,1,ford galaxie 500\r\n14,8,318,150,4096,13,71,1,plymouth fury iii\r\n12,8,383,180,4955,11.5,71,1,dodge monaco (sw)\r\n13,8,400,170,4746,12,71,1,ford country squire (sw)\r\n13,8,400,175,5140,12,71,1,pontiac safari (sw)\r\n18,6,258,110,2962,13.5,71,1,amc hornet sportabout (sw)\r\n22,4,140,72,2408,19,71,1,chevrolet vega (sw)\r\n19,6,250,100,3282,15,71,1,pontiac firebird\r\n18,6,250,88,3139,14.5,71,1,ford mustang\r\n23,4,122,86,2220,14,71,1,mercury capri 2000\r\n28,4,116,90,2123,14,71,2,opel 1900\r\n30,4,79,70,2074,19.5,71,2,peugeot 304\r\n30,4,88,76,2065,14.5,71,2,fiat 124b\r\n31,4,71,65,1773,19,71,3,toyota corolla 1200\r\n35,4,72,69,1613,18,71,3,datsun 1200\r\n27,4,97,60,1834,19,71,2,volkswagen model 111\r\n26,4,91,70,1955,20.5,71,1,plymouth cricket\r\n24,4,113,95,2278,15.5,72,3,toyota corona hardtop\r\n25,4,97.5,80,2126,17,72,1,dodge colt hardtop\r\n23,4,97,54,2254,23.5,72,2,volkswagen type 3\r\n20,4,140,90,2408,19.5,72,1,chevrolet vega\r\n21,4,122,86,2226,16.5,72,1,ford pinto runabout\r\n13,8,350,165,4274,12,72,1,chevrolet impala\r\n14,8,400,175,4385,12,72,1,pontiac catalina\r\n15,8,318,150,4135,13.5,72,1,plymouth fury iii\r\n14,8,351,153,4129,13,72,1,ford galaxie 500\r\n17,8,304,150,3672,11.5,72,1,amc ambassador sst\r\n11,8,429,208,4633,11,72,1,mercury marquis\r\n13,8,350,155,4502,13.5,72,1,buick lesabre custom\r\n12,8,350,160,4456,13.5,72,1,oldsmobile delta 88 royale\r\n13,8,400,190,4422,12.5,72,1,chrysler newport royal\r\n19,3,70,97,2330,13.5,72,3,mazda rx2 coupe\r\n15,8,304,150,3892,12.5,72,1,amc matador (sw)\r\n13,8,307,130,4098,14,72,1,chevrolet chevelle concours (sw)\r\n13,8,302,140,4294,16,72,1,ford gran torino (sw)\r\n14,8,318,150,4077,14,72,1,plymouth satellite custom (sw)\r\n18,4,121,112,2933,14.5,72,2,volvo 145e (sw)\r\n22,4,121,76,2511,18,72,2,volkswagen 411 (sw)\r\n21,4,120,87,2979,19.5,72,2,peugeot 504 (sw)\r\n26,4,96,69,2189,18,72,2,renault 12 (sw)\r\n22,4,122,86,2395,16,72,1,ford pinto (sw)\r\n28,4,97,92,2288,17,72,3,datsun 510 (sw)\r\n23,4,120,97,2506,14.5,72,3,toyouta corona mark ii (sw)\r\n28,4,98,80,2164,15,72,1,dodge colt (sw)\r\n27,4,97,88,2100,16.5,72,3,toyota corolla 1600 (sw)\r\n13,8,350,175,4100,13,73,1,buick century 350\r\n14,8,304,150,3672,11.5,73,1,amc matador\r\n13,8,350,145,3988,13,73,1,chevrolet malibu\r\n14,8,302,137,4042,14.5,73,1,ford gran torino\r\n15,8,318,150,3777,12.5,73,1,dodge coronet custom\r\n12,8,429,198,4952,11.5,73,1,mercury marquis brougham\r\n13,8,400,150,4464,12,73,1,chevrolet caprice classic\r\n13,8,351,158,4363,13,73,1,ford ltd\r\n14,8,318,150,4237,14.5,73,1,plymouth fury gran sedan\r\n13,8,440,215,4735,11,73,1,chrysler new yorker brougham\r\n12,8,455,225,4951,11,73,1,buick electra 225 custom\r\n13,8,360,175,3821,11,73,1,amc ambassador brougham\r\n18,6,225,105,3121,16.5,73,1,plymouth valiant\r\n16,6,250,100,3278,18,73,1,chevrolet nova custom\r\n18,6,232,100,2945,16,73,1,amc hornet\r\n18,6,250,88,3021,16.5,73,1,ford maverick\r\n23,6,198,95,2904,16,73,1,plymouth duster\r\n26,4,97,46,1950,21,73,2,volkswagen super beetle\r\n11,8,400,150,4997,14,73,1,chevrolet impala\r\n12,8,400,167,4906,12.5,73,1,ford country\r\n13,8,360,170,4654,13,73,1,plymouth custom suburb\r\n12,8,350,180,4499,12.5,73,1,oldsmobile vista cruiser\r\n18,6,232,100,2789,15,73,1,amc gremlin\r\n20,4,97,88,2279,19,73,3,toyota carina\r\n21,4,140,72,2401,19.5,73,1,chevrolet vega\r\n22,4,108,94,2379,16.5,73,3,datsun 610\r\n18,3,70,90,2124,13.5,73,3,maxda rx3\r\n19,4,122,85,2310,18.5,73,1,ford pinto\r\n21,6,155,107,2472,14,73,1,mercury capri v6\r\n26,4,98,90,2265,15.5,73,2,fiat 124 sport coupe\r\n15,8,350,145,4082,13,73,1,chevrolet monte carlo s\r\n16,8,400,230,4278,9.5,73,1,pontiac grand prix\r\n29,4,68,49,1867,19.5,73,2,fiat 128\r\n24,4,116,75,2158,15.5,73,2,opel manta\r\n20,4,114,91,2582,14,73,2,audi 100ls\r\n19,4,121,112,2868,15.5,73,2,volvo 144ea\r\n15,8,318,150,3399,11,73,1,dodge dart custom\r\n24,4,121,110,2660,14,73,2,saab 99le\r\n20,6,156,122,2807,13.5,73,3,toyota mark ii\r\n11,8,350,180,3664,11,73,1,oldsmobile omega\r\n20,6,198,95,3102,16.5,74,1,plymouth duster\r\n21,6,200,?,2875,17,74,1,ford maverick\r\n19,6,232,100,2901,16,74,1,amc hornet\r\n15,6,250,100,3336,17,74,1,chevrolet nova\r\n31,4,79,67,1950,19,74,3,datsun b210\r\n26,4,122,80,2451,16.5,74,1,ford pinto\r\n32,4,71,65,1836,21,74,3,toyota corolla 1200\r\n25,4,140,75,2542,17,74,1,chevrolet vega\r\n16,6,250,100,3781,17,74,1,chevrolet chevelle malibu classic\r\n16,6,258,110,3632,18,74,1,amc matador\r\n18,6,225,105,3613,16.5,74,1,plymouth satellite sebring\r\n16,8,302,140,4141,14,74,1,ford gran torino\r\n13,8,350,150,4699,14.5,74,1,buick century luxus (sw)\r\n14,8,318,150,4457,13.5,74,1,dodge coronet custom (sw)\r\n14,8,302,140,4638,16,74,1,ford gran torino (sw)\r\n14,8,304,150,4257,15.5,74,1,amc matador (sw)\r\n29,4,98,83,2219,16.5,74,2,audi fox\r\n26,4,79,67,1963,15.5,74,2,volkswagen dasher\r\n26,4,97,78,2300,14.5,74,2,opel manta\r\n31,4,76,52,1649,16.5,74,3,toyota corona\r\n32,4,83,61,2003,19,74,3,datsun 710\r\n28,4,90,75,2125,14.5,74,1,dodge colt\r\n24,4,90,75,2108,15.5,74,2,fiat 128\r\n26,4,116,75,2246,14,74,2,fiat 124 tc\r\n24,4,120,97,2489,15,74,3,honda civic\r\n26,4,108,93,2391,15.5,74,3,subaru\r\n31,4,79,67,2000,16,74,2,fiat x1.9\r\n19,6,225,95,3264,16,75,1,plymouth valiant custom\r\n18,6,250,105,3459,16,75,1,chevrolet nova\r\n15,6,250,72,3432,21,75,1,mercury monarch\r\n15,6,250,72,3158,19.5,75,1,ford maverick\r\n16,8,400,170,4668,11.5,75,1,pontiac catalina\r\n15,8,350,145,4440,14,75,1,chevrolet bel air\r\n16,8,318,150,4498,14.5,75,1,plymouth grand fury\r\n14,8,351,148,4657,13.5,75,1,ford ltd\r\n17,6,231,110,3907,21,75,1,buick century\r\n16,6,250,105,3897,18.5,75,1,chevroelt chevelle malibu\r\n15,6,258,110,3730,19,75,1,amc matador\r\n18,6,225,95,3785,19,75,1,plymouth fury\r\n21,6,231,110,3039,15,75,1,buick skyhawk\r\n20,8,262,110,3221,13.5,75,1,chevrolet monza 2+2\r\n13,8,302,129,3169,12,75,1,ford mustang ii\r\n29,4,97,75,2171,16,75,3,toyota corolla\r\n23,4,140,83,2639,17,75,1,ford pinto\r\n20,6,232,100,2914,16,75,1,amc gremlin\r\n23,4,140,78,2592,18.5,75,1,pontiac astro\r\n24,4,134,96,2702,13.5,75,3,toyota corona\r\n25,4,90,71,2223,16.5,75,2,volkswagen dasher\r\n24,4,119,97,2545,17,75,3,datsun 710\r\n18,6,171,97,2984,14.5,75,1,ford pinto\r\n29,4,90,70,1937,14,75,2,volkswagen rabbit\r\n19,6,232,90,3211,17,75,1,amc pacer\r\n23,4,115,95,2694,15,75,2,audi 100ls\r\n23,4,120,88,2957,17,75,2,peugeot 504\r\n22,4,121,98,2945,14.5,75,2,volvo 244dl\r\n25,4,121,115,2671,13.5,75,2,saab 99le\r\n33,4,91,53,1795,17.5,75,3,honda civic cvcc\r\n28,4,107,86,2464,15.5,76,2,fiat 131\r\n25,4,116,81,2220,16.9,76,2,opel 1900\r\n25,4,140,92,2572,14.9,76,1,capri ii\r\n26,4,98,79,2255,17.7,76,1,dodge colt\r\n27,4,101,83,2202,15.3,76,2,renault 12tl\r\n17.5,8,305,140,4215,13,76,1,chevrolet chevelle malibu classic\r\n16,8,318,150,4190,13,76,1,dodge coronet brougham\r\n15.5,8,304,120,3962,13.9,76,1,amc matador\r\n14.5,8,351,152,4215,12.8,76,1,ford gran torino\r\n22,6,225,100,3233,15.4,76,1,plymouth valiant\r\n22,6,250,105,3353,14.5,76,1,chevrolet nova\r\n24,6,200,81,3012,17.6,76,1,ford maverick\r\n22.5,6,232,90,3085,17.6,76,1,amc hornet\r\n29,4,85,52,2035,22.2,76,1,chevrolet chevette\r\n24.5,4,98,60,2164,22.1,76,1,chevrolet woody\r\n29,4,90,70,1937,14.2,76,2,vw rabbit\r\n33,4,91,53,1795,17.4,76,3,honda civic\r\n20,6,225,100,3651,17.7,76,1,dodge aspen se\r\n18,6,250,78,3574,21,76,1,ford granada ghia\r\n18.5,6,250,110,3645,16.2,76,1,pontiac ventura sj\r\n17.5,6,258,95,3193,17.8,76,1,amc pacer d/l\r\n29.5,4,97,71,1825,12.2,76,2,volkswagen rabbit\r\n32,4,85,70,1990,17,76,3,datsun b-210\r\n28,4,97,75,2155,16.4,76,3,toyota corolla\r\n26.5,4,140,72,2565,13.6,76,1,ford pinto\r\n20,4,130,102,3150,15.7,76,2,volvo 245\r\n13,8,318,150,3940,13.2,76,1,plymouth volare premier v8\r\n19,4,120,88,3270,21.9,76,2,peugeot 504\r\n19,6,156,108,2930,15.5,76,3,toyota mark ii\r\n16.5,6,168,120,3820,16.7,76,2,mercedes-benz 280s\r\n16.5,8,350,180,4380,12.1,76,1,cadillac seville\r\n13,8,350,145,4055,12,76,1,chevy c10\r\n13,8,302,130,3870,15,76,1,ford f108\r\n13,8,318,150,3755,14,76,1,dodge d100\r\n31.5,4,98,68,2045,18.5,77,3,honda accord cvcc\r\n30,4,111,80,2155,14.8,77,1,buick opel isuzu deluxe\r\n36,4,79,58,1825,18.6,77,2,renault 5 gtl\r\n25.5,4,122,96,2300,15.5,77,1,plymouth arrow gs\r\n33.5,4,85,70,1945,16.8,77,3,datsun f-10 hatchback\r\n17.5,8,305,145,3880,12.5,77,1,chevrolet caprice classic\r\n17,8,260,110,4060,19,77,1,oldsmobile cutlass supreme\r\n15.5,8,318,145,4140,13.7,77,1,dodge monaco brougham\r\n15,8,302,130,4295,14.9,77,1,mercury cougar brougham\r\n17.5,6,250,110,3520,16.4,77,1,chevrolet concours\r\n20.5,6,231,105,3425,16.9,77,1,buick skylark\r\n19,6,225,100,3630,17.7,77,1,plymouth volare custom\r\n18.5,6,250,98,3525,19,77,1,ford granada\r\n16,8,400,180,4220,11.1,77,1,pontiac grand prix lj\r\n15.5,8,350,170,4165,11.4,77,1,chevrolet monte carlo landau\r\n15.5,8,400,190,4325,12.2,77,1,chrysler cordoba\r\n16,8,351,149,4335,14.5,77,1,ford thunderbird\r\n29,4,97,78,1940,14.5,77,2,volkswagen rabbit custom\r\n24.5,4,151,88,2740,16,77,1,pontiac sunbird coupe\r\n26,4,97,75,2265,18.2,77,3,toyota corolla liftback\r\n25.5,4,140,89,2755,15.8,77,1,ford mustang ii 2+2\r\n30.5,4,98,63,2051,17,77,1,chevrolet chevette\r\n33.5,4,98,83,2075,15.9,77,1,dodge colt m/m\r\n30,4,97,67,1985,16.4,77,3,subaru dl\r\n30.5,4,97,78,2190,14.1,77,2,volkswagen dasher\r\n22,6,146,97,2815,14.5,77,3,datsun 810\r\n21.5,4,121,110,2600,12.8,77,2,bmw 320i\r\n21.5,3,80,110,2720,13.5,77,3,mazda rx-4\r\n43.1,4,90,48,1985,21.5,78,2,volkswagen rabbit custom diesel\r\n36.1,4,98,66,1800,14.4,78,1,ford fiesta\r\n32.8,4,78,52,1985,19.4,78,3,mazda glc deluxe\r\n39.4,4,85,70,2070,18.6,78,3,datsun b210 gx\r\n36.1,4,91,60,1800,16.4,78,3,honda civic cvcc\r\n19.9,8,260,110,3365,15.5,78,1,oldsmobile cutlass salon brougham\r\n19.4,8,318,140,3735,13.2,78,1,dodge diplomat\r\n20.2,8,302,139,3570,12.8,78,1,mercury monarch ghia\r\n19.2,6,231,105,3535,19.2,78,1,pontiac phoenix lj\r\n20.5,6,200,95,3155,18.2,78,1,chevrolet malibu\r\n20.2,6,200,85,2965,15.8,78,1,ford fairmont (auto)\r\n25.1,4,140,88,2720,15.4,78,1,ford fairmont (man)\r\n20.5,6,225,100,3430,17.2,78,1,plymouth volare\r\n19.4,6,232,90,3210,17.2,78,1,amc concord\r\n20.6,6,231,105,3380,15.8,78,1,buick century special\r\n20.8,6,200,85,3070,16.7,78,1,mercury zephyr\r\n18.6,6,225,110,3620,18.7,78,1,dodge aspen\r\n18.1,6,258,120,3410,15.1,78,1,amc concord d/l\r\n19.2,8,305,145,3425,13.2,78,1,chevrolet monte carlo landau\r\n17.7,6,231,165,3445,13.4,78,1,buick regal sport coupe (turbo)\r\n18.1,8,302,139,3205,11.2,78,1,ford futura\r\n17.5,8,318,140,4080,13.7,78,1,dodge magnum xe\r\n30,4,98,68,2155,16.5,78,1,chevrolet chevette\r\n27.5,4,134,95,2560,14.2,78,3,toyota corona\r\n27.2,4,119,97,2300,14.7,78,3,datsun 510\r\n30.9,4,105,75,2230,14.5,78,1,dodge omni\r\n21.1,4,134,95,2515,14.8,78,3,toyota celica gt liftback\r\n23.2,4,156,105,2745,16.7,78,1,plymouth sapporo\r\n23.8,4,151,85,2855,17.6,78,1,oldsmobile starfire sx\r\n23.9,4,119,97,2405,14.9,78,3,datsun 200-sx\r\n20.3,5,131,103,2830,15.9,78,2,audi 5000\r\n17,6,163,125,3140,13.6,78,2,volvo 264gl\r\n21.6,4,121,115,2795,15.7,78,2,saab 99gle\r\n16.2,6,163,133,3410,15.8,78,2,peugeot 604sl\r\n31.5,4,89,71,1990,14.9,78,2,volkswagen scirocco\r\n29.5,4,98,68,2135,16.6,78,3,honda accord lx\r\n21.5,6,231,115,3245,15.4,79,1,pontiac lemans v6\r\n19.8,6,200,85,2990,18.2,79,1,mercury zephyr 6\r\n22.3,4,140,88,2890,17.3,79,1,ford fairmont 4\r\n20.2,6,232,90,3265,18.2,79,1,amc concord dl 6\r\n20.6,6,225,110,3360,16.6,79,1,dodge aspen 6\r\n17,8,305,130,3840,15.4,79,1,chevrolet caprice classic\r\n17.6,8,302,129,3725,13.4,79,1,ford ltd landau\r\n16.5,8,351,138,3955,13.2,79,1,mercury grand marquis\r\n18.2,8,318,135,3830,15.2,79,1,dodge st. regis\r\n16.9,8,350,155,4360,14.9,79,1,buick estate wagon (sw)\r\n15.5,8,351,142,4054,14.3,79,1,ford country squire (sw)\r\n19.2,8,267,125,3605,15,79,1,chevrolet malibu classic (sw)\r\n18.5,8,360,150,3940,13,79,1,chrysler lebaron town @ country (sw)\r\n31.9,4,89,71,1925,14,79,2,vw rabbit custom\r\n34.1,4,86,65,1975,15.2,79,3,maxda glc deluxe\r\n35.7,4,98,80,1915,14.4,79,1,dodge colt hatchback custom\r\n27.4,4,121,80,2670,15,79,1,amc spirit dl\r\n25.4,5,183,77,3530,20.1,79,2,mercedes benz 300d\r\n23,8,350,125,3900,17.4,79,1,cadillac eldorado\r\n27.2,4,141,71,3190,24.8,79,2,peugeot 504\r\n23.9,8,260,90,3420,22.2,79,1,oldsmobile cutlass salon brougham\r\n34.2,4,105,70,2200,13.2,79,1,plymouth horizon\r\n34.5,4,105,70,2150,14.9,79,1,plymouth horizon tc3\r\n31.8,4,85,65,2020,19.2,79,3,datsun 210\r\n37.3,4,91,69,2130,14.7,79,2,fiat strada custom\r\n28.4,4,151,90,2670,16,79,1,buick skylark limited\r\n28.8,6,173,115,2595,11.3,79,1,chevrolet citation\r\n26.8,6,173,115,2700,12.9,79,1,oldsmobile omega brougham\r\n33.5,4,151,90,2556,13.2,79,1,pontiac phoenix\r\n41.5,4,98,76,2144,14.7,80,2,vw rabbit\r\n38.1,4,89,60,1968,18.8,80,3,toyota corolla tercel\r\n32.1,4,98,70,2120,15.5,80,1,chevrolet chevette\r\n37.2,4,86,65,2019,16.4,80,3,datsun 310\r\n28,4,151,90,2678,16.5,80,1,chevrolet citation\r\n26.4,4,140,88,2870,18.1,80,1,ford fairmont\r\n24.3,4,151,90,3003,20.1,80,1,amc concord\r\n19.1,6,225,90,3381,18.7,80,1,dodge aspen\r\n34.3,4,97,78,2188,15.8,80,2,audi 4000\r\n29.8,4,134,90,2711,15.5,80,3,toyota corona liftback\r\n31.3,4,120,75,2542,17.5,80,3,mazda 626\r\n37,4,119,92,2434,15,80,3,datsun 510 hatchback\r\n32.2,4,108,75,2265,15.2,80,3,toyota corolla\r\n46.6,4,86,65,2110,17.9,80,3,mazda glc\r\n27.9,4,156,105,2800,14.4,80,1,dodge colt\r\n40.8,4,85,65,2110,19.2,80,3,datsun 210\r\n44.3,4,90,48,2085,21.7,80,2,vw rabbit c (diesel)\r\n43.4,4,90,48,2335,23.7,80,2,vw dasher (diesel)\r\n36.4,5,121,67,2950,19.9,80,2,audi 5000s (diesel)\r\n30,4,146,67,3250,21.8,80,2,mercedes-benz 240d\r\n44.6,4,91,67,1850,13.8,80,3,honda civic 1500 gl\r\n40.9,4,85,?,1835,17.3,80,2,renault lecar deluxe\r\n33.8,4,97,67,2145,18,80,3,subaru dl\r\n29.8,4,89,62,1845,15.3,80,2,vokswagen rabbit\r\n32.7,6,168,132,2910,11.4,80,3,datsun 280-zx\r\n23.7,3,70,100,2420,12.5,80,3,mazda rx-7 gs\r\n35,4,122,88,2500,15.1,80,2,triumph tr7 coupe\r\n23.6,4,140,?,2905,14.3,80,1,ford mustang cobra\r\n32.4,4,107,72,2290,17,80,3,honda accord\r\n27.2,4,135,84,2490,15.7,81,1,plymouth reliant\r\n26.6,4,151,84,2635,16.4,81,1,buick skylark\r\n25.8,4,156,92,2620,14.4,81,1,dodge aries wagon (sw)\r\n23.5,6,173,110,2725,12.6,81,1,chevrolet citation\r\n30,4,135,84,2385,12.9,81,1,plymouth reliant\r\n39.1,4,79,58,1755,16.9,81,3,toyota starlet\r\n39,4,86,64,1875,16.4,81,1,plymouth champ\r\n35.1,4,81,60,1760,16.1,81,3,honda civic 1300\r\n32.3,4,97,67,2065,17.8,81,3,subaru\r\n37,4,85,65,1975,19.4,81,3,datsun 210 mpg\r\n37.7,4,89,62,2050,17.3,81,3,toyota tercel\r\n34.1,4,91,68,1985,16,81,3,mazda glc 4\r\n34.7,4,105,63,2215,14.9,81,1,plymouth horizon 4\r\n34.4,4,98,65,2045,16.2,81,1,ford escort 4w\r\n29.9,4,98,65,2380,20.7,81,1,ford escort 2h\r\n33,4,105,74,2190,14.2,81,2,volkswagen jetta\r\n34.5,4,100,?,2320,15.8,81,2,renault 18i\r\n33.7,4,107,75,2210,14.4,81,3,honda prelude\r\n32.4,4,108,75,2350,16.8,81,3,toyota corolla\r\n32.9,4,119,100,2615,14.8,81,3,datsun 200sx\r\n31.6,4,120,74,2635,18.3,81,3,mazda 626\r\n28.1,4,141,80,3230,20.4,81,2,peugeot 505s turbo diesel\r\n30.7,6,145,76,3160,19.6,81,2,volvo diesel\r\n25.4,6,168,116,2900,12.6,81,3,toyota cressida\r\n24.2,6,146,120,2930,13.8,81,3,datsun 810 maxima\r\n22.4,6,231,110,3415,15.8,81,1,buick century\r\n26.6,8,350,105,3725,19,81,1,oldsmobile cutlass ls\r\n20.2,6,200,88,3060,17.1,81,1,ford granada gl\r\n17.6,6,225,85,3465,16.6,81,1,chrysler lebaron salon\r\n28,4,112,88,2605,19.6,82,1,chevrolet cavalier\r\n27,4,112,88,2640,18.6,82,1,chevrolet cavalier wagon\r\n34,4,112,88,2395,18,82,1,chevrolet cavalier 2-door\r\n31,4,112,85,2575,16.2,82,1,pontiac j2000 se hatchback\r\n29,4,135,84,2525,16,82,1,dodge aries se\r\n27,4,151,90,2735,18,82,1,pontiac phoenix\r\n24,4,140,92,2865,16.4,82,1,ford fairmont futura\r\n23,4,151,?,3035,20.5,82,1,amc concord dl\r\n36,4,105,74,1980,15.3,82,2,volkswagen rabbit l\r\n37,4,91,68,2025,18.2,82,3,mazda glc custom l\r\n31,4,91,68,1970,17.6,82,3,mazda glc custom\r\n38,4,105,63,2125,14.7,82,1,plymouth horizon miser\r\n36,4,98,70,2125,17.3,82,1,mercury lynx l\r\n36,4,120,88,2160,14.5,82,3,nissan stanza xe\r\n36,4,107,75,2205,14.5,82,3,honda accord\r\n34,4,108,70,2245,16.9,82,3,toyota corolla\r\n38,4,91,67,1965,15,82,3,honda civic\r\n32,4,91,67,1965,15.7,82,3,honda civic (auto)\r\n38,4,91,67,1995,16.2,82,3,datsun 310 gx\r\n25,6,181,110,2945,16.4,82,1,buick century limited\r\n38,6,262,85,3015,17,82,1,oldsmobile cutlass ciera (diesel)\r\n26,4,156,92,2585,14.5,82,1,chrysler lebaron medallion\r\n22,6,232,112,2835,14.7,82,1,ford granada l\r\n32,4,144,96,2665,13.9,82,3,toyota celica gt\r\n36,4,135,84,2370,13,82,1,dodge charger 2.2\r\n27,4,151,90,2950,17.3,82,1,chevrolet camaro\r\n27,4,140,86,2790,15.6,82,1,ford mustang gl\r\n44,4,97,52,2130,24.6,82,2,vw pickup\r\n32,4,135,84,2295,11.6,82,1,dodge rampage\r\n28,4,120,79,2625,18.6,82,1,ford ranger\r\n31,4,119,82,2720,19.4,82,1,chevy s-10\r\n"}

In [10]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler, PolynomialFeatures
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv("auto-mpg.csv")
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [7]:
df["car name"].nunique()

305

In [8]:
df.horsepower.unique()

array(['130', '165', '150', '140', '198', '220', '215', '225', '190',
       '170', '160', '95', '97', '85', '88', '46', '87', '90', '113',
       '200', '210', '193', '?', '100', '105', '175', '153', '180', '110',
       '72', '86', '70', '76', '65', '69', '60', '80', '54', '208', '155',
       '112', '92', '145', '137', '158', '167', '94', '107', '230', '49',
       '75', '91', '122', '67', '83', '78', '52', '61', '93', '148',
       '129', '96', '71', '98', '115', '53', '81', '79', '120', '152',
       '102', '108', '68', '58', '149', '89', '63', '48', '66', '139',
       '103', '125', '133', '138', '135', '142', '77', '62', '132', '84',
       '64', '74', '116', '82'], dtype=object)

In [11]:
df = df.replace("?", np.nan)

In [12]:
df.isna().sum()/len(df)

mpg             0.000000
cylinders       0.000000
displacement    0.000000
horsepower      0.015075
weight          0.000000
acceleration    0.000000
model year      0.000000
origin          0.000000
car name        0.000000
dtype: float64

In [13]:
df = df.dropna()

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    object
 4   weight        392 non-null    int64
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64
 7   origin        392 non-null    int64
 8   car name      392 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 30.6+ KB

In [15]:
df.horsepower = df.horsepower.astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 392 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    int64
 4   weight        392 non-null    int64
 5   acceleration  392 non-null    float64
 6   model year    392 non-null    int64
 7   origin        392 non-null    int64
 8   car name      392 non-null    object
dtypes: float64(3), int64(5), object(1)
memory usage: 30.6+ KB

In [22]:
## goal: predict mpg

X = df.drop(columns=["mpg", "car name"])
y = df["mpg"]

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=42)

In [24]:
def model_inplace(scaler, model, X_train, X_test, y_train, y_test):
  x_train = scaler.fit_transform(X_train)
  x_test = scaler.transform(X_test)
  model.fit(x_train, y_train)
  print("r2 score on train set", model.score(x_train,y_train))
  print("r2 score on test set", model.score(x_test,y_test))

In [25]:
baseline_model = LinearRegression()

## regularisations
ridge = Ridge(alpha = 0.3) ## L2 regulariser
lasso  = Lasso(alpha = 0.1) ## L1 regulariser

In [26]:
scaler1 = StandardScaler()
scaler2 = MinMaxScaler()
scaler3 = PolynomialFeatures(degree=2, interaction_only= True) ## check documentation

In [27]:
x_train_poly = scaler3.fit_transform(X_train)
x_train_poly

array([[1.0000e+00, 8.0000e+00, 3.0700e+02, ..., 1.0080e+03, 1.4000e+01,
        7.2000e+01],
       [1.0000e+00, 4.0000e+00, 9.0000e+01, ..., 1.1470e+03, 3.1000e+01,
        1.4800e+02],
       [1.0000e+00, 4.0000e+00, 1.0500e+02, ..., 1.2546e+03, 3.0600e+01,
        1.6400e+02],
       ...,
       [1.0000e+00, 4.0000e+00, 1.5100e+02, ..., 1.3728e+03, 1.7600e+01,
        7.8000e+01],
       [1.0000e+00, 4.0000e+00, 9.8000e+01, ..., 1.6767e+03, 2.0700e+01,
        8.1000e+01],
       [1.0000e+00, 8.0000e+00, 4.0000e+02, ..., 1.0220e+03, 1.4000e+01,
        7.3000e+01]])

In [28]:
x_train_poly.shape ## dimensionality augmentation

(352, 29)

In [29]:
model_inplace(scaler1, baseline_model, X_train, X_test, y_train, y_test)

r2 score on train set 0.8174881977424256
r2 score on test set 0.8550071364633914

In [30]:
model_inplace(scaler2, baseline_model, X_train, X_test, y_train, y_test)

r2 score on train set 0.8174881977424255
r2 score on test set 0.8550071364633913

In [31]:
model_inplace(scaler3, baseline_model, X_train, X_test, y_train, y_test)
## good example of how feature engineering is important in the AI lifecycle

r2 score on train set 0.886957351140881
r2 score on test set 0.9021610449251577

In [32]:
model_inplace(scaler1, lasso, X_train, X_test, y_train, y_test)

r2 score on train set 0.8149740267566365
r2 score on test set 0.8445789626772027

In [33]:
model_inplace(scaler2, lasso, X_train, X_test, y_train, y_test)

r2 score on train set 0.8103704029089804
r2 score on test set 0.8425935057775985

In [34]:
model_inplace(scaler3, lasso, X_train, X_test, y_train, y_test)

r2 score on train set 0.8767323827360345
r2 score on test set 0.893057199455408

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.382e+03, tolerance: 2.144e+00
  model = cd_fast.enet_coordinate_descent(

In [45]:
## hyper parameter tunning: choosing the best parameters of the model

from sklearn.model_selection import GridSearchCV ## for loop in your parameters

ridge = Lasso()
params = {"alpha": np.arange(0,1000,100)}
#0,10,20,30,40 .... dividing the interval [0,1000] in 100 pieces
grid = GridSearchCV(lasso, param_grid= params, cv =10, verbose=1)
X_train = scaler1.fit_transform(X_train)
X_test = scaler1.transform(X_test)
grid.fit(X_train, y_train)
best_model = grid.best_estimator_
print("coefficients model", best_model.coef_)
print("score on train set", best_model.score(X_train, y_train))
print("score on test set", best_model.score(X_test, y_test))

#feature selection is taking features that are irrelevant to the model

print("columns that were removed by Lasso", X.columns[best_model.coef_==0])
print("columns that were NOT removed by Lasso", X.columns[best_model.coef_ !=0])
print("best alpha", grid.best_params_)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.720e+03, tolerance: 1.989e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.840e+03, tolerance: 1.947e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.733e+03, tolerance: 1.964e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.759e+03, tolerance: 1.881e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.697e+03, tolerance: 1.937e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.596e+03, tolerance: 1.797e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.785e+03, tolerance: 1.960e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.807e+03, tolerance: 1.956e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.780e+03, tolerance: 1.926e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.832e+03, tolerance: 1.931e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

coefficients model [-0.70264897  1.68720797 -0.60718499 -5.31244743  0.15801816  2.75033518
  1.17302218]
score on train set 0.8174881977424256
score on test set 0.8550071364633915
columns that were removed by Lasso Index([], dtype='object')
columns that were NOT removed by Lasso Index(['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration',
       'model year', 'origin'],
      dtype='object')
best alpha {'alpha': np.int64(0)}

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.956e+03, tolerance: 2.144e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(

In [42]:
x_train_poly

array([[1.0000e+00, 8.0000e+00, 3.0700e+02, ..., 1.0080e+03, 1.4000e+01,
        7.2000e+01],
       [1.0000e+00, 4.0000e+00, 9.0000e+01, ..., 1.1470e+03, 3.1000e+01,
        1.4800e+02],
       [1.0000e+00, 4.0000e+00, 1.0500e+02, ..., 1.2546e+03, 3.0600e+01,
        1.6400e+02],
       ...,
       [1.0000e+00, 4.0000e+00, 1.5100e+02, ..., 1.3728e+03, 1.7600e+01,
        7.8000e+01],
       [1.0000e+00, 4.0000e+00, 9.8000e+01, ..., 1.6767e+03, 2.0700e+01,
        8.1000e+01],
       [1.0000e+00, 8.0000e+00, 4.0000e+02, ..., 1.0220e+03, 1.4000e+01,
        7.3000e+01]])

In [49]:
## hyper parameter tunning: choosing the best parameters of the model

from sklearn.model_selection import GridSearchCV ## for loop in your parameters

ridge = Ridge()
params = {"alpha": np.arange(0,1,100)}
#0,10,20,30,40 .... dividing the interval [0,1000] in 100 pieces
grid = GridSearchCV(lasso, param_grid= params, cv =10, verbose=1)
X_train = scaler1.fit_transform(X_train)
X_test = scaler1.transform(X_test)
grid.fit(X_train, y_train)
best_model = grid.best_estimator_
print("coefficients model", best_model.coef_)
print("score on train set", best_model.score(X_train, y_train))
print("score on test set", best_model.score(X_test, y_test))

#feature selection is taking features that are irrelevant to the model

#print("columns that were removed by Lasso", X.columns[best_model.coef_==0])
#print("columns that were NOT removed by Lasso", X.columns[best_model.coef_ !=0])
print("best alpha", grid.best_params_)

Fitting 10 folds for each of 1 candidates, totalling 10 fits
coefficients model [-0.70264897  1.68720797 -0.60718499 -5.31244743  0.15801816  2.75033518
  1.17302218]
score on train set 0.8174881977424256
score on test set 0.8550071364633915
best alpha {'alpha': np.int64(0)}

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.720e+03, tolerance: 1.989e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.840e+03, tolerance: 1.947e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.733e+03, tolerance: 1.964e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.759e+03, tolerance: 1.881e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.697e+03, tolerance: 1.937e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.596e+03, tolerance: 1.797e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.785e+03, tolerance: 1.960e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.807e+03, tolerance: 1.956e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.780e+03, tolerance: 1.926e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.832e+03, tolerance: 1.931e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.956e+03, tolerance: 2.144e+00 Linear regression models with null weight for the l1 regularization term are more efficiently fitted using one of the solvers implemented in sklearn.linear_model.Ridge/RidgeCV instead.
  model = cd_fast.enet_coordinate_descent(